src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing_page"),
    path('core/', include('core.urls', namespace='core')),
    path('central_admin/', include('inventory.urls.central_admin', namespace='central_admin')),
    path('sub_admin/', include('inventory.urls.sub_admin', namespace='sub_admin')),
    path('room_incharge/', include('inventory.urls.room_incharge', namespace='room_incharge')),
    path('students/', include('inventory.urls.student', namespace='student')),
]

src/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
     path('login/', views.LoginView.as_view(), name='login'),
     path('register/', views.UserRegisterView.as_view(), name='register'),
     path('logout/', views.LogoutView.as_view(), name='logout'),
     path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
     path('reset-password/', views.ResetPasswordView.as_view(), name='reset_password'),
     path('done-password-reset/', views.DonePasswordResetView.as_view(),
          name='done_password_reset'),
     path('confirm-password-reset/<uidb64>/<token>/',
          views.ConfirmPasswordResetView.as_view(), name='confirm_password_reset'),
     path('complete-password-reset/', views.CompletePasswordResetView.as_view(),
          name='complete_password_reset'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blixtro {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo-icon.svg' %}">
    <script src="{% static 'utils/htmx/htmx.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/d2ef0bf498.js" crossorigin="anonymous"></script>
    <link href="{% static 'utils/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block style %}{% endblock style %}
</head>

<body class="bg-light">
    <div class="initial-wrap">
        
        <!-- Navbar -->
        {% block navbar %}{% endblock navbar %}

        <!-- Sidebar -->
        {% block sidebar %}{% endblock sidebar %}

        <!-- Main Content -->
        <section class="main-content">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </section>

    </div>
    {% block scripts %}{% endblock scripts %}
    <script src="{% static 'utils/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

src/templates/landing_page.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Landing Page</title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <style>
    .hero {
      position: relative;
      background: url('https://images.unsplash.com/photo-1721937718756-3bfec49f42a2?q=80&w=3137&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D') no-repeat center center;
      background-size: cover;
      border-radius: 10px;
      color: white;
      padding: 100px 0;
    }

    .hero::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.801);
      border-radius: 10px;
    }

    .hero h1 {
      font-size: 2rem;
      font-weight: bold;
    }

    .hero p {
      font-size: 1rem;
    }
    
    .content{
      position: relative;
      z-index: 1;
    }

    .btn-custom {
      background-color: #007bff;
      border-color: #007bff;
      color: white;
    }

    .btn-custom:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }

    .navbar{
      border-radius: 10px;
    }
  </style>
</head>

<body>
  <div class="container">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light mt-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{% static 'images/logo.svg' %}" width="130px" alt="Blixtro Logo"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'student:report_issue' %}">Report Issue</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:login' %}">Login</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="row hero text-center mt-5">
      <div class="col info">
        <div class="content">
          <h1>Blixtro Inventory Management System</h1>
          <p>Detailed item cards, batch tracking, quick stock reports, and accurate inventory cost calculations |
            Blixtro Online Inventory Management System</p>
        </div>
      </div>
    </div>

  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

src/templates/sidebar_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blixtro {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo-icon.svg' %}">
    <script src="{% static 'utils/htmx/htmx.min.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />
    <link href="{% static 'utils/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block style %}{% endblock style %}
</head>

<body class="bg-light">
    <div class="initial-wrap">
        
        <!-- Navbar -->
        {% block navbar %}{% endblock navbar %}

        <!-- Sidebar -->
        {% block sidebar %}{% endblock sidebar %}

        <!-- Main Content -->
        <section class="main-content">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </section>

    </div>
    {% block scripts %}{% endblock scripts %}
    <script src="{% static 'utils/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>