src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing_page"),
    path('core/', include('core.urls', namespace='core')),
    path('central_admin/', include('inventory.urls.central_admin', namespace='central_admin')),
    path('sub_admin/', include('inventory.urls.sub_admin', namespace='sub_admin')),
    path('room_incharge/', include('inventory.urls.room_incharge', namespace='room_incharge')),
    path('students/', include('inventory.urls.student', namespace='student')),
]

src/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
     path('login/', views.LoginView.as_view(), name='login'),
     path('register/', views.UserRegisterView.as_view(), name='register'),
     path('logout/', views.LogoutView.as_view(), name='logout'),
     path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
     path('reset-password/', views.ResetPasswordView.as_view(), name='reset_password'),
     path('done-password-reset/', views.DonePasswordResetView.as_view(),
          name='done_password_reset'),
     path('confirm-password-reset/<uidb64>/<token>/',
          views.ConfirmPasswordResetView.as_view(), name='confirm_password_reset'),
     path('complete-password-reset/', views.CompletePasswordResetView.as_view(),
          name='complete_password_reset'),
]

src/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from . user_manager import UserManager
from django.utils.text import slugify
from config.utils import generate_unique_slug
from django.db.models.signals import post_delete
from django.dispatch import receiver
    
    
class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_set',  # Add this line
        blank=True,
        help_text=_('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
        verbose_name=_('groups'),
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions_set',  # Add this line
        blank=True,
        help_text=_('Specific permissions for this user.'),
        verbose_name=_('user permissions'),
    )
    

class Organisation(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, db_index=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            self.slug = generate_unique_slug(self, base_slug)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    

class Department(models.Model):
    organisation = models.ForeignKey(Organisation,on_delete=models.CASCADE)
    department_name = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    udpated_on = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f"{self.department_name}-{self.organisation}")
            self.slug = generate_unique_slug(self, base_slug)
        super().save(*args, **kwargs)
    
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='profile')
    org = models.ForeignKey(Organisation, null=True, on_delete=models.SET_NULL, related_name='org')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    is_central_admin = models.BooleanField(_('is central admin'), default=False)
    is_incharge = models.BooleanField(_('is room incharge'), default=False)
    is_student = models.BooleanField(_('is student'), default=False)
    slug = models.SlugField(unique=True, db_index=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f"{self.first_name}-{self.last_name}{self.org}")
            self.slug = generate_unique_slug(self, base_slug)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{str(self.first_name)} {str(self.last_name)}"
    

# Signals
# Delete User that is associated with UserProfile on its delete
@receiver(post_delete, sender=UserProfile)
def delete_user_on_profile_delete(sender, instance, **kwargs):
    try:
        user = instance.user
        user.delete()
        print(f"User {user.email} and associated profile deleted successfully.")
    except Exception as e:
        print(f"Error occurred while deleting user: {str(e)}")    

src/core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from config.mixins import form_mixin

User = get_user_model()



class CustomAuthenticationForm(form_mixin.BootstrapFormMixin, AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'required': True}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'required': True}))
    
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''

        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        

class UserRegisterForm(form_mixin.BootstrapFormMixin, UserCreationForm):
    org_name = forms.CharField(max_length=200, required=True, label='Organisation name')
    first_name = forms.CharField(max_length=200, required=True)
    last_name = forms.CharField(max_length=200, required=True)

    class Meta:
        model = User
        fields = ['org_name', 'first_name', 'last_name', 'email',]  
        
        

src/core/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.db import transaction
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, 
    PasswordResetCompleteView, PasswordResetConfirmView, 
    PasswordResetDoneView, PasswordResetView
    )
from django.contrib.auth import login
from django.urls import reverse_lazy
from . forms import CustomAuthenticationForm, UserRegisterForm
from django.views.generic import CreateView
from core.models import UserProfile, Organisation
from django.contrib.auth import get_user_model
from config.mixins.access_mixins import RedirectLoggedInUsersMixin

User = get_user_model()


class LandingPageView(RedirectLoggedInUsersMixin, TemplateView):
    template_name = 'landing_page.html'
    
    
class LoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'core/login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect('landing_page')
    

class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')
    
    @transaction.atomic
    def form_valid(self, form):
        user = form.save()
        
        org_name = form.cleaned_data.get('org_name')
        org = Organisation.objects.create(
            name = org_name,
        )
        
        # Create user profile
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        UserProfile.objects.create(
            user=user, 
            org = org,
            first_name=first_name, 
            last_name=last_name, 
            is_central_admin=True
            )
        
        login(self.request, user)
        return redirect('landing_page')
    

class LogoutView(LogoutView):
    template_name = 'core/logout.html'


class ChangePasswordView(PasswordChangeView):
    template_name = 'core/change_password.html'
    success_url = reverse_lazy('landing_page')


class ResetPasswordView(PasswordResetView):
    email_template_name = 'core/password_reset/password_reset_email.html'
    html_email_template_name = 'core/password_reset/password_reset_email.html'
    subject_template_name = 'core/password_reset/password_reset_subject.txt'
    success_url = reverse_lazy('core:done_password_reset')
    template_name = 'core/password_reset/password_reset_form.html'


class DonePasswordResetView(PasswordResetDoneView):
    template_name = 'core/password_reset/password_reset_done.html'


class ConfirmPasswordResetView(PasswordResetConfirmView):
    success_url = reverse_lazy('core:complete_password_reset')
    template_name = 'core/password_reset/password_reset_confirm.html'


class CompletePasswordResetView(PasswordResetCompleteView):
    template_name = 'core/password_reset/password_reset_complete.html'
    
    

src/templates/core/password_reset/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% block title %} | Password Reset Complete{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'styles/core/forms_style/style.css' %}">
{% endblock style %}

{% block content %}
<h2>Password Reset Complete</h2>
<p>Your Password has been set. You may go ahead and sign in</p>
<div class="button-group">
    <a href="{% url 'core:login' %}"><button class="btn btn-primary" type="button">Sign in</button></a>
</div>
{% endblock content %}

src/templates/core/password_reset/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %} | Password Reset{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'styles/core/forms_style/style.css' %}">
{% endblock style %}


{% block content %}
<h3>Create password</h3>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Reset Password</button>
</form>
{% endblock content %}

src/templates/core/password_reset/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'styles/core/forms_style/style.css' %}">
{% endblock style %}

{% block content %}
<div>
    <h2>Password Reset Email Sent</h2>
<p>We've emailed you instructions for setting your password,if an account exists with the email you entered.You should
    receive them shortly.if you don't receive an email,please make sure you've entered the address you registered
    with,and check your spam folder</p>
</div>
{% endblock content %}

src/templates/core/password_reset/password_reset_email.html
{% load i18n %}
{% autoescape off %}
    <p>
        You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.
    </p>
    <p>
        Please go to the following page and choose a new password:
    </p>
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'core:confirm_password_reset' uidb64=uid token=token %}
    {% endblock %}
    <p>Your email, in case you've forgotten: {{ user.email }}</p>
    <p>Thanks for using our site!</p>
    <p>The {{ site_name }} team.</p>
{% endautoescape %}

src/templates/core/password_reset/password_reset_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}| Reset-Password{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'styles/core/forms_style/style.css' %}">
{% endblock style %}

{% block content %}
<h3>Enter your email</h3>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock content %}